---
title: "% sexed specimens against % females"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, message = FALSE, warning = FALSE}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork)
library(png)
library(knitr)
library(broom)
library(here)
library(ggfortify)

#install.packages("remotes")
#remotes::install_github("sckott/rphylopic")
library(rphylopic)

# Colour blind friendly palette
# First is grey
# Colour blind friendly palette
cbPalette <- c("#999999", "#a53606", "#b32db5", "#881a58", "#0e288e", "#164c64")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r, message = FALSE, warning = FALSE}
# Read in all the specimen data
specimens_all <- read_csv(here("data/all-specimen-data-unsexed-2021-07.csv")) 
# Add column of sexed versus unsexed
specimens_all <- 
  specimens_all %>%
  mutate(sexed = case_when(is.na(sex) ~ "unsexed", !is.na(sex) ~ "sexed"))
```

## Is this biasing our results?

```{r}
# Extract data for % female
ds_female <-
  specimens_all %>%
  filter(!is.na(sex)) %>%
  group_by(class) %>%
  add_count(binomial, name = "n") %>%
  add_count(binomial, sex, name = "nn") %>%
  select(class, order, binomial, sex, n, nn) %>%
  # Add in data for species with no males or no females
  complete(sex, nesting(class, order, binomial, n), fill = list(nn = 0)) %>%
  filter(n >= 10 & sex == "Female") %>%
  mutate(percentf = round(nn/n*100, 2)) %>%
  select(class, order, binomial, percentf) %>%
  distinct() %>%
  group_by(class, order, binomial) %>%
  summarise('% female' = round(mean(percentf), 2))

# Extract % sexed
ds_sexed <-
  specimens_all %>%
  group_by(class) %>%
  add_count(binomial, name = "n") %>%
  add_count(binomial, sexed, name = "nn") %>%
  select(class, order, binomial, sexed, n, nn) %>%
  # Add in data for species with no males or no females
  complete(sexed, nesting(order, class, binomial, n), fill = list(nn = 0)) %>%
  filter(n >= 10 & sexed == "sexed") %>%
  mutate(percent= round(nn/n*100, 2)) %>%
  select(class, order, binomial, percent) %>%
  distinct() %>%
  group_by(class, order, binomial) %>%
  summarise('% sexed' = round(mean(percent), 2))

# Combine datasets
all <- 
  ds_sexed %>%
  left_join(ds_female, by = c("class", "order", "binomial")) %>%
  select(class, order, binomial, `% female`, `% sexed`) %>%
  # Add zeros for species with no sexed individuals
  mutate(`% female` = case_when(is.na(`% female`) ~ 0, 
                                TRUE ~ as.numeric(`% female`)))
```

```{r}
ggplot(all, aes(x = `% female`, y = `% sexed`, colour = class, fill = class)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = 'lm', alpha = 0.2) +
  theme_bw(base_size = 14) +
  xlab("% female") +
  ylab("% sexed") +
  theme(legend.title = element_blank())+
  scale_colour_manual(values = c(cbPalette[3], cbPalette[5])) +
  scale_fill_manual(values = c(cbPalette[3], cbPalette[5]))

##ggsave(here("figures/unsexed-females-percent-correlation.png"), height = 5)

```

```{r}
# Fit some models for Amphibians and Reptiles
allA <- all %>% filter(class == "Amphibians")
allR <- all %>% filter(class == "Reptiles")

modelA <- lm(log(`% sexed`+1) ~ log(`% female`+1), data = allA)
autoplot(modelA)
tidy(anova(modelA))
summary(modelA)

modelR <- lm(log(`% sexed`+1) ~ log(`% female`+1), data = allR)
autoplot(modelR)
tidy(anova(modelR))
summary(modelR)
```
